# Generated by Django 2.2.1 on 2019-05-31 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=100, unique=True)),
                ('PhoneNo', models.CharField(max_length=10, unique=True)),
                ('Subject', models.CharField(max_length=200)),
                ('Message', models.CharField(max_length=500)),
                ('Comment', models.CharField(max_length=200)),
            ],
        ),
    ]
